# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.private_cloud_create_subscription import PrivateCloudCreateSubscription  # noqa: E501

class TestPrivateCloudCreateSubscription(unittest.TestCase):
    """PrivateCloudCreateSubscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrivateCloudCreateSubscription:
        """Test PrivateCloudCreateSubscription
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrivateCloudCreateSubscription`
        """
        model = PrivateCloudCreateSubscription()  # noqa: E501
        if include_optional:
            return PrivateCloudCreateSubscription(
                subscription_id = 56
            )
        else:
            return PrivateCloudCreateSubscription(
        )
        """

    def testPrivateCloudCreateSubscription(self):
        """Test PrivateCloudCreateSubscription"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
