# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.private_cloud_deployment_profile import PrivateCloudDeploymentProfile

class TestPrivateCloudDeploymentProfile(unittest.TestCase):
    """PrivateCloudDeploymentProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrivateCloudDeploymentProfile:
        """Test PrivateCloudDeploymentProfile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrivateCloudDeploymentProfile`
        """
        model = PrivateCloudDeploymentProfile()
        if include_optional:
            return PrivateCloudDeploymentProfile(
                description = ''
            )
        else:
            return PrivateCloudDeploymentProfile(
        )
        """

    def testPrivateCloudDeploymentProfile(self):
        """Test PrivateCloudDeploymentProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
