# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.private_cloud_api import PrivateCloudApi


class TestPrivateCloudApi(unittest.TestCase):
    """PrivateCloudApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PrivateCloudApi()

    def tearDown(self) -> None:
        pass

    def test_private_cloud_get(self) -> None:
        """Test case for private_cloud_get

        """
        pass

    def test_private_cloud_id_locations_name_delete(self) -> None:
        """Test case for private_cloud_id_locations_name_delete

        """
        pass

    def test_private_cloud_id_locations_put(self) -> None:
        """Test case for private_cloud_id_locations_put

        """
        pass

    def test_private_cloud_id_whitelist_post(self) -> None:
        """Test case for private_cloud_id_whitelist_post

        """
        pass

    def test_private_cloud_locations_get(self) -> None:
        """Test case for private_cloud_locations_get

        """
        pass

    def test_private_cloud_post(self) -> None:
        """Test case for private_cloud_post

        """
        pass

    def test_private_cloud_put(self) -> None:
        """Test case for private_cloud_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
