# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.private_cloud_post import PrivateCloudPOST

class TestPrivateCloudPOST(unittest.TestCase):
    """PrivateCloudPOST unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrivateCloudPOST:
        """Test PrivateCloudPOST
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrivateCloudPOST`
        """
        model = PrivateCloudPOST()
        if include_optional:
            return PrivateCloudPOST(
                cloud_status = 'BlockedForEdit',
                vm_name = '',
                vm_user = '',
                vm_password = '',
                database_user = '',
                database_password = '',
                shared_secret = '',
                public_ip = '',
                internal_ip = '',
                subnet = '',
                vpn_gateway = '',
                region = '',
                boxwise_url = '',
                boxwise_version = openapi_client.models.private_cloud_ike_version.PrivateCloud_IKE_Version(
                    version = '', ),
                deployment_profile = openapi_client.models.private_cloud_2_deployment_profile.PrivateCloud_2_DeploymentProfile(
                    description = '', ),
                environment_id = openapi_client.models.private_cloud_2_environment_id.PrivateCloud_2_EnvironmentId(
                    env_id = '', ),
                cloud_size = openapi_client.models.private_cloud_post_cloud_size.PrivateCloud_POST_CloudSize(
                    code = '', ),
                subscription = openapi_client.models.private_cloud_post_subscription.PrivateCloud_POST_Subscription(
                    subscription_id = 56, ),
                github_access_token_url = '',
                worker_status = ''
            )
        else:
            return PrivateCloudPOST(
        )
        """

    def testPrivateCloudPOST(self):
        """Test PrivateCloudPOST"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
