# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.location_create_environment_id_private_cloud_location_vpnike_version import LocationCreateEnvironmentIdPrivateCloudLocationVPNIKEVersion  # noqa: E501

class TestLocationCreateEnvironmentIdPrivateCloudLocationVPNIKEVersion(unittest.TestCase):
    """LocationCreateEnvironmentIdPrivateCloudLocationVPNIKEVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LocationCreateEnvironmentIdPrivateCloudLocationVPNIKEVersion:
        """Test LocationCreateEnvironmentIdPrivateCloudLocationVPNIKEVersion
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LocationCreateEnvironmentIdPrivateCloudLocationVPNIKEVersion`
        """
        model = LocationCreateEnvironmentIdPrivateCloudLocationVPNIKEVersion()  # noqa: E501
        if include_optional:
            return LocationCreateEnvironmentIdPrivateCloudLocationVPNIKEVersion(
                version = ''
            )
        else:
            return LocationCreateEnvironmentIdPrivateCloudLocationVPNIKEVersion(
        )
        """

    def testLocationCreateEnvironmentIdPrivateCloudLocationVPNIKEVersion(self):
        """Test LocationCreateEnvironmentIdPrivateCloudLocationVPNIKEVersion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
