# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.locations_api import LocationsApi  # noqa: E501


class TestLocationsApi(unittest.TestCase):
    """LocationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LocationsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_locations_id_loc_whitelist_post(self) -> None:
        """Test case for locations_id_loc_whitelist_post

        """
        pass

    def test_locations_post(self) -> None:
        """Test case for locations_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
