# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.subnet import Subnet  # noqa: E501

class TestSubnet(unittest.TestCase):
    """Subnet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Subnet:
        """Test Subnet
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Subnet`
        """
        model = Subnet()  # noqa: E501
        if include_optional:
            return Subnet(
                subnet = '',
                cidr_notation = '',
                first_assignable_host = '',
                last_assignable_host = ''
            )
        else:
            return Subnet(
        )
        """

    def testSubnet(self):
        """Test Subnet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
