# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.private_cloud_subscription import PrivateCloudSubscription  # noqa: E501

class TestPrivateCloudSubscription(unittest.TestCase):
    """PrivateCloudSubscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrivateCloudSubscription:
        """Test PrivateCloudSubscription
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrivateCloudSubscription`
        """
        model = PrivateCloudSubscription()  # noqa: E501
        if include_optional:
            return PrivateCloudSubscription(
                subscription_id = 56,
                license_id = 56
            )
        else:
            return PrivateCloudSubscription(
        )
        """

    def testPrivateCloudSubscription(self):
        """Test PrivateCloudSubscription"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
