# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.location_update_private_cloud_location_vpns import LocationUpdatePrivateCloudLocationVPNs  # noqa: E501

class TestLocationUpdatePrivateCloudLocationVPNs(unittest.TestCase):
    """LocationUpdatePrivateCloudLocationVPNs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LocationUpdatePrivateCloudLocationVPNs:
        """Test LocationUpdatePrivateCloudLocationVPNs
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LocationUpdatePrivateCloudLocationVPNs`
        """
        model = LocationUpdatePrivateCloudLocationVPNs()  # noqa: E501
        if include_optional:
            return LocationUpdatePrivateCloudLocationVPNs(
                location = '',
                status = ''
            )
        else:
            return LocationUpdatePrivateCloudLocationVPNs(
        )
        """

    def testLocationUpdatePrivateCloudLocationVPNs(self):
        """Test LocationUpdatePrivateCloudLocationVPNs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
