# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.private_cloud2_environment_id import PrivateCloud2EnvironmentId  # noqa: E501

class TestPrivateCloud2EnvironmentId(unittest.TestCase):
    """PrivateCloud2EnvironmentId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrivateCloud2EnvironmentId:
        """Test PrivateCloud2EnvironmentId
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrivateCloud2EnvironmentId`
        """
        model = PrivateCloud2EnvironmentId()  # noqa: E501
        if include_optional:
            return PrivateCloud2EnvironmentId(
                env_id = ''
            )
        else:
            return PrivateCloud2EnvironmentId(
        )
        """

    def testPrivateCloud2EnvironmentId(self):
        """Test PrivateCloud2EnvironmentId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
