# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.location_update import LocationUpdate  # noqa: E501

class TestLocationUpdate(unittest.TestCase):
    """LocationUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LocationUpdate:
        """Test LocationUpdate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LocationUpdate`
        """
        model = LocationUpdate()  # noqa: E501
        if include_optional:
            return LocationUpdate(
                env_id = '',
                private_cloud = openapi_client.models.location_update_private_cloud.LocationUpdate_PrivateCloud(
                    location_vpns = openapi_client.models.location_update_private_cloud_location_vpns.LocationUpdate_PrivateCloud_Location_VPNs(
                        location = '', 
                        status = '', ), )
            )
        else:
            return LocationUpdate(
        )
        """

    def testLocationUpdate(self):
        """Test LocationUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
