# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.private_cloud_ike_version import PrivateCloudIKEVersion

class TestPrivateCloudIKEVersion(unittest.TestCase):
    """PrivateCloudIKEVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrivateCloudIKEVersion:
        """Test PrivateCloudIKEVersion
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrivateCloudIKEVersion`
        """
        model = PrivateCloudIKEVersion()
        if include_optional:
            return PrivateCloudIKEVersion(
                version = ''
            )
        else:
            return PrivateCloudIKEVersion(
        )
        """

    def testPrivateCloudIKEVersion(self):
        """Test PrivateCloudIKEVersion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
