# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.location_create_environment_id import LocationCreateEnvironmentId  # noqa: E501

class TestLocationCreateEnvironmentId(unittest.TestCase):
    """LocationCreateEnvironmentId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LocationCreateEnvironmentId:
        """Test LocationCreateEnvironmentId
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LocationCreateEnvironmentId`
        """
        model = LocationCreateEnvironmentId()  # noqa: E501
        if include_optional:
            return LocationCreateEnvironmentId(
                env_id = '',
                private_cloud = openapi_client.models.location_create_environment_id_private_cloud.LocationCreate_EnvironmentId_PrivateCloud(
                    location_vpn = openapi_client.models.location_create_environment_id_private_cloud_location_vpn.LocationCreate_EnvironmentId_PrivateCloud_Location_VPN(
                        location = '', 
                        peer_ip = '', 
                        gate_way_ip = '', 
                        subnet = '', 
                        status = '', 
                        ike_version = openapi_client.models.location_create_environment_id_private_cloud_location_vpn_ike_version.LocationCreate_EnvironmentId_PrivateCloud_Location_VPN_IKE_Version(
                            version = '', ), ), )
            )
        else:
            return LocationCreateEnvironmentId(
        )
        """

    def testLocationCreateEnvironmentId(self):
        """Test LocationCreateEnvironmentId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
