# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.private_cloud_create import PrivateCloudCreate  # noqa: E501

class TestPrivateCloudCreate(unittest.TestCase):
    """PrivateCloudCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrivateCloudCreate:
        """Test PrivateCloudCreate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrivateCloudCreate`
        """
        model = PrivateCloudCreate()  # noqa: E501
        if include_optional:
            return PrivateCloudCreate(
                cloud_status = 'BlockedForEdit',
                vm_name = '',
                vm_user = '',
                vm_password = '',
                database_user = '',
                database_password = '',
                shared_secret = '',
                public_ip = '',
                internal_ip = '',
                subnet = '',
                vpn_gateway = '',
                region = '',
                boxwise_url = '',
                boxwise_version = openapi_client.models.private_cloud_boxwise_version.PrivateCloud_BoxwiseVersion(
                    version = '', 
                    name = '', 
                    _id = 56, ),
                deployment_profile = openapi_client.models.private_cloud_deployment_profile.PrivateCloud_DeploymentProfile(
                    description = '', ),
                environment_id = openapi_client.models.private_cloud_environment_id.PrivateCloud_EnvironmentId(
                    env_id = '', ),
                cloud_size = openapi_client.models.private_cloud_create_cloud_size.PrivateCloudCreate_CloudSize(
                    code = '', ),
                subscription = openapi_client.models.private_cloud_create_subscription.PrivateCloudCreate_Subscription(
                    subscription_id = 56, )
            )
        else:
            return PrivateCloudCreate(
        )
        """

    def testPrivateCloudCreate(self):
        """Test PrivateCloudCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
