# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr
from openapi_client.models.location_create_environment_id_private_cloud import LocationCreateEnvironmentIdPrivateCloud

class LocationCreateEnvironmentId(BaseModel):
    """
    LocationCreateEnvironmentId
    """
    env_id: Optional[StrictStr] = Field(None, alias="Env_Id")
    private_cloud: Optional[LocationCreateEnvironmentIdPrivateCloud] = Field(None, alias="PrivateCloud")
    __properties = ["Env_Id", "PrivateCloud"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LocationCreateEnvironmentId:
        """Create an instance of LocationCreateEnvironmentId from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of private_cloud
        if self.private_cloud:
            _dict['PrivateCloud'] = self.private_cloud.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LocationCreateEnvironmentId:
        """Create an instance of LocationCreateEnvironmentId from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LocationCreateEnvironmentId.parse_obj(obj)

        _obj = LocationCreateEnvironmentId.parse_obj({
            "env_id": obj.get("Env_Id"),
            "private_cloud": LocationCreateEnvironmentIdPrivateCloud.from_dict(obj.get("PrivateCloud")) if obj.get("PrivateCloud") is not None else None
        })
        return _obj


