# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field
from openapi_client.models.location_create_environment_id import LocationCreateEnvironmentId

class LocationCreate(BaseModel):
    """
    LocationCreate
    """
    environment_id: Optional[LocationCreateEnvironmentId] = Field(None, alias="EnvironmentId")
    __properties = ["EnvironmentId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LocationCreate:
        """Create an instance of LocationCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of environment_id
        if self.environment_id:
            _dict['EnvironmentId'] = self.environment_id.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LocationCreate:
        """Create an instance of LocationCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LocationCreate.parse_obj(obj)

        _obj = LocationCreate.parse_obj({
            "environment_id": LocationCreateEnvironmentId.from_dict(obj.get("EnvironmentId")) if obj.get("EnvironmentId") is not None else None
        })
        return _obj


