# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr, field_validator
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class LocationVPN(BaseModel):
    """
    LocationVPN
    """ # noqa: E501
    location: Optional[StrictStr] = Field(default=None, alias="Location")
    peer_ip: Optional[StrictStr] = Field(default=None, alias="Peer_Ip")
    gate_way_ip: Optional[StrictStr] = Field(default=None, alias="GateWay_IP")
    subnet: Optional[StrictStr] = Field(default=None, alias="Subnet")
    status: Optional[StrictStr] = Field(default=None, alias="Status")
    shared_secret: Optional[StrictStr] = Field(default=None, alias="SharedSecret")
    whitelist: Optional[StrictStr] = Field(default=None, alias="Whitelist")
    __properties: ClassVar[List[str]] = ["Location", "Peer_Ip", "GateWay_IP", "Subnet", "Status", "SharedSecret", "Whitelist"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('BlockedForEdit', 'WaitForCreation', 'InProgress', 'Active', 'Error', 'WaitForDeletion', 'Deleted', 'WaitForEdit'):
            raise ValueError("must be one of enum values ('BlockedForEdit', 'WaitForCreation', 'InProgress', 'Active', 'Error', 'WaitForDeletion', 'Deleted', 'WaitForEdit')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LocationVPN from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of LocationVPN from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Location": obj.get("Location"),
            "Peer_Ip": obj.get("Peer_Ip"),
            "GateWay_IP": obj.get("GateWay_IP"),
            "Subnet": obj.get("Subnet"),
            "Status": obj.get("Status"),
            "SharedSecret": obj.get("SharedSecret"),
            "Whitelist": obj.get("Whitelist")
        })
        return _obj


