# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, validator
from openapi_client.models.private_cloud_boxwise_version import PrivateCloudBoxwiseVersion
from openapi_client.models.private_cloud_create_cloud_size import PrivateCloudCreateCloudSize
from openapi_client.models.private_cloud_create_subscription import PrivateCloudCreateSubscription
from openapi_client.models.private_cloud_deployment_profile import PrivateCloudDeploymentProfile
from openapi_client.models.private_cloud_environment_id import PrivateCloudEnvironmentId

class PrivateCloudCreate(BaseModel):
    """
    PrivateCloudCreate
    """
    cloud_status: Optional[StrictStr] = Field(None, alias="CloudStatus")
    vm_name: Optional[StrictStr] = Field(None, alias="VM_Name")
    vm_user: Optional[StrictStr] = Field(None, alias="VM_User")
    vm_password: Optional[StrictStr] = Field(None, alias="VM_Password")
    database_user: Optional[StrictStr] = Field(None, alias="Database_User")
    database_password: Optional[StrictStr] = Field(None, alias="Database_Password")
    shared_secret: Optional[StrictStr] = Field(None, alias="SharedSecret")
    public_ip: Optional[StrictStr] = Field(None, alias="Public_IP")
    internal_ip: Optional[StrictStr] = Field(None, alias="Internal_IP")
    subnet: Optional[StrictStr] = Field(None, alias="Subnet")
    vpn_gateway: Optional[StrictStr] = Field(None, alias="VPN_Gateway")
    region: Optional[StrictStr] = Field(None, alias="Region")
    boxwise_url: Optional[StrictStr] = Field(None, alias="Boxwise_url")
    boxwise_version: Optional[PrivateCloudBoxwiseVersion] = Field(None, alias="BoxwiseVersion")
    deployment_profile: Optional[PrivateCloudDeploymentProfile] = Field(None, alias="DeploymentProfile")
    environment_id: Optional[PrivateCloudEnvironmentId] = Field(None, alias="EnvironmentId")
    cloud_size: Optional[PrivateCloudCreateCloudSize] = Field(None, alias="CloudSize")
    subscription: Optional[PrivateCloudCreateSubscription] = Field(None, alias="Subscription")
    __properties = ["CloudStatus", "VM_Name", "VM_User", "VM_Password", "Database_User", "Database_Password", "SharedSecret", "Public_IP", "Internal_IP", "Subnet", "VPN_Gateway", "Region", "Boxwise_url", "BoxwiseVersion", "DeploymentProfile", "EnvironmentId", "CloudSize", "Subscription"]

    @validator('cloud_status')
    def cloud_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('BlockedForEdit', 'WaitForCreation', 'InProgress', 'Active', 'Error', 'WaitForDeletion', 'Deleted', 'WaitForEdit'):
            raise ValueError("must be one of enum values ('BlockedForEdit', 'WaitForCreation', 'InProgress', 'Active', 'Error', 'WaitForDeletion', 'Deleted', 'WaitForEdit')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PrivateCloudCreate:
        """Create an instance of PrivateCloudCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of boxwise_version
        if self.boxwise_version:
            _dict['BoxwiseVersion'] = self.boxwise_version.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deployment_profile
        if self.deployment_profile:
            _dict['DeploymentProfile'] = self.deployment_profile.to_dict()
        # override the default output from pydantic by calling `to_dict()` of environment_id
        if self.environment_id:
            _dict['EnvironmentId'] = self.environment_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cloud_size
        if self.cloud_size:
            _dict['CloudSize'] = self.cloud_size.to_dict()
        # override the default output from pydantic by calling `to_dict()` of subscription
        if self.subscription:
            _dict['Subscription'] = self.subscription.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PrivateCloudCreate:
        """Create an instance of PrivateCloudCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PrivateCloudCreate.parse_obj(obj)

        _obj = PrivateCloudCreate.parse_obj({
            "cloud_status": obj.get("CloudStatus"),
            "vm_name": obj.get("VM_Name"),
            "vm_user": obj.get("VM_User"),
            "vm_password": obj.get("VM_Password"),
            "database_user": obj.get("Database_User"),
            "database_password": obj.get("Database_Password"),
            "shared_secret": obj.get("SharedSecret"),
            "public_ip": obj.get("Public_IP"),
            "internal_ip": obj.get("Internal_IP"),
            "subnet": obj.get("Subnet"),
            "vpn_gateway": obj.get("VPN_Gateway"),
            "region": obj.get("Region"),
            "boxwise_url": obj.get("Boxwise_url"),
            "boxwise_version": PrivateCloudBoxwiseVersion.from_dict(obj.get("BoxwiseVersion")) if obj.get("BoxwiseVersion") is not None else None,
            "deployment_profile": PrivateCloudDeploymentProfile.from_dict(obj.get("DeploymentProfile")) if obj.get("DeploymentProfile") is not None else None,
            "environment_id": PrivateCloudEnvironmentId.from_dict(obj.get("EnvironmentId")) if obj.get("EnvironmentId") is not None else None,
            "cloud_size": PrivateCloudCreateCloudSize.from_dict(obj.get("CloudSize")) if obj.get("CloudSize") is not None else None,
            "subscription": PrivateCloudCreateSubscription.from_dict(obj.get("Subscription")) if obj.get("Subscription") is not None else None
        })
        return _obj


