# coding: utf-8

"""
    CloudAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr, field_validator
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PrivateCloudPUTPrivateCloud(BaseModel):
    """
    PrivateCloudPUTPrivateCloud
    """ # noqa: E501
    cloud_status: Optional[StrictStr] = Field(default=None, alias="CloudStatus")
    vm_name: Optional[StrictStr] = Field(default=None, alias="VM_Name")
    vm_user: Optional[StrictStr] = Field(default=None, alias="VM_User")
    vm_password: Optional[StrictStr] = Field(default=None, alias="VM_Password")
    database_user: Optional[StrictStr] = Field(default=None, alias="Database_User")
    public_ip: Optional[StrictStr] = Field(default=None, alias="Public_IP")
    internal_ip: Optional[StrictStr] = Field(default=None, alias="Internal_IP")
    subnet: Optional[StrictStr] = Field(default=None, alias="Subnet")
    vpn_gateway: Optional[StrictStr] = Field(default=None, alias="VPN_Gateway")
    region: Optional[StrictStr] = Field(default=None, alias="Region")
    boxwise_url: Optional[StrictStr] = Field(default=None, alias="Boxwise_url")
    whitelist: Optional[StrictStr] = Field(default=None, alias="Whitelist")
    github_access_token_url: Optional[StrictStr] = Field(default=None, alias="GithubAccessToken_url")
    worker_status: Optional[StrictStr] = Field(default=None, alias="Worker_status")
    __properties: ClassVar[List[str]] = ["CloudStatus", "VM_Name", "VM_User", "VM_Password", "Database_User", "Public_IP", "Internal_IP", "Subnet", "VPN_Gateway", "Region", "Boxwise_url", "Whitelist", "GithubAccessToken_url", "Worker_status"]

    @field_validator('cloud_status')
    def cloud_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('BlockedForEdit', 'WaitForCreation', 'InProgress', 'Active', 'Error', 'WaitForDeletion', 'Deleted', 'WaitForEdit'):
            raise ValueError("must be one of enum values ('BlockedForEdit', 'WaitForCreation', 'InProgress', 'Active', 'Error', 'WaitForDeletion', 'Deleted', 'WaitForEdit')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PrivateCloudPUTPrivateCloud from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PrivateCloudPUTPrivateCloud from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "CloudStatus": obj.get("CloudStatus"),
            "VM_Name": obj.get("VM_Name"),
            "VM_User": obj.get("VM_User"),
            "VM_Password": obj.get("VM_Password"),
            "Database_User": obj.get("Database_User"),
            "Public_IP": obj.get("Public_IP"),
            "Internal_IP": obj.get("Internal_IP"),
            "Subnet": obj.get("Subnet"),
            "VPN_Gateway": obj.get("VPN_Gateway"),
            "Region": obj.get("Region"),
            "Boxwise_url": obj.get("Boxwise_url"),
            "Whitelist": obj.get("Whitelist"),
            "GithubAccessToken_url": obj.get("GithubAccessToken_url"),
            "Worker_status": obj.get("Worker_status")
        })
        return _obj


